version: "3"

services:

  mysql:
    container_name: mysql
    image: mysql:5.7
    networks:
      - interna
    environment:
      - MYSQL_ROOT_PASSWORD=mysql-secret
      - MYSQL_DATABASE=wordpress

  wordpress:
    container_name: wordpress
    image: wordpress
    ports:
      - 80:80
    networks:
      - interna
    depends_on:
      - mysql
    environment:
    - WORDPRESS_DB_HOST=mysql
    - WORDPRESS_DB_PASSWORD=mysql-secret
    - WORDPRESS_DB_USER=root

networks:
    interna: